theme: jekyll-theme-minimal
title: Matthew Schawe
description: Bookmark this to keep an eye on my project updates!

exclude:
  - .gitignore
  - "*.code-workspace"
  - Gemfile
  - Gemfile.lock
  - README.md